server.port=8888
spring.application.name=config-server

# ============================
# Native Profile for local files (no git)
# ============================
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:${user.dir}/../config-repo

spring.cloud.compatibility-verifier.enabled=false

logging.level.org.springframework.cloud=INFO

# =============================================
# Enregistrement dans Eureka
# =============================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

